### PR TITLE
Hide WeakPairMap: it is package private

### PR DESCRIPTION
**Pull request by JnRouvignac**
See https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/lang/WeakPairMap.java

### CODE REVIEW

**Comment by marchof** [comment]
Dear @JnRouvignac, the diff is automatically generated from the actual JDK APIs. Manual patches will not work, as they will be overwritten every night.

So instead we need to investigate why this inner-inner classes actually show up in the JDK API.

**Comment by JnRouvignac** [comment]
I assumed so. The PR seemed like a good way to start the conversation and show the problem.
Where is the code doing the diff?

**Comment by JnRouvignac** [comment]
Is it https://github.com/AdoptOpenJDK/jdk-api-diff ?

**Comment by JnRouvignac** [comment]
Or rather https://github.com/siom79/japicmp/blob/master/japicmp/src/main/java/japicmp/cmp/ClassesComparator.java actually

**Comment by marchof** [comment]
Neither. It is my own tool stack that is not (yet) publicly available.

**Comment by marchof** [comment]
Technically these class are indeed public. When I run the following snippet with JDK 11

```
import java.lang.reflect.Modifier;

public class PublicAPIs {

	public static void main(String[] args) throws Exception {
		Class<?> clazz = Class.forName("java.lang.WeakPairMap$Pair$Lookup");
		System.out.println(Modifier.isPublic(clazz.getModifiers()));
	}

}
```

it prints

```
true
```

If you think this is an error please report it to the OpenJDK project.

**Comment by marchof** [comment]
FYI, I did a systematic search over JDK 11 and found the following public inner classes nested in private classes:

```
java/awt/EventFilter$FilterAction
java/lang/FdLibm$Cbrt
java/lang/FdLibm$Hypot
java/lang/FdLibm$Pow
java/lang/LiveStackFrame$PrimitiveSlot
java/lang/WeakPairMap$Pair$Lookup
java/lang/WeakPairMap$Pair$Weak
java/lang/invoke/ClassSpecializer$Factory
java/lang/invoke/ClassSpecializer$SpeciesData
java/util/stream/Node$Builder
java/util/stream/Node$OfDouble
java/util/stream/Node$OfInt
java/util/stream/Node$OfLong
java/util/stream/Node$OfPrimitive
java/util/stream/Sink$ChainedDouble
java/util/stream/Sink$ChainedInt
java/util/stream/Sink$ChainedLong
java/util/stream/Sink$ChainedReference
java/util/stream/Sink$OfDouble
java/util/stream/Sink$OfInt
java/util/stream/Sink$OfLong
javax/swing/MultiUIDefaults$MultiUIDefaultsEnumerator$Type
javax/swing/plaf/basic/DragRecognitionSupport$BeforeDrag
javax/swing/plaf/metal/MetalSplitPaneDivider$MetalDividerLayout
javax/swing/plaf/nimbus/Effect$ArrayCache
javax/swing/text/html/AccessibleHTML$HTMLAccessibleContext
javax/swing/text/html/AccessibleHTML$IconElementInfo$IconAccessibleContext
javax/swing/text/html/AccessibleHTML$TableElementInfo$TableAccessibleContext
javax/swing/text/html/AccessibleHTML$TextElementInfo$TextAccessibleContext
javax/swing/text/html/TableView$RowView
javax/xml/catalog/GroupEntry$PreferType
javax/xml/catalog/GroupEntry$ResolveType
```

**Comment by JnRouvignac** [comment]
Oh that's interesting.

Your comment made me look at it again as I clearly remember not seeing a `public` keyword. And indeed that's the case.

These classes are public because they are members of interfaces (from JLS):

```
All members of interfaces are implicitly `public`.
```

**Comment by JnRouvignac** [comment]
Sorry for wasting your time.

BTW thank you for your project. It is very helpful.

**Comment by marchof** [comment]
@JnRouvignac No need to be sorry, this was quite an interesting observation.

If I find some time I will discuss this at the OpenJDK project.

It looks like it is impossible to compile actual Java source code with these classes. So maybe the diff reports can exclude nested classes of non-visible parents at all.

**Comment by JnRouvignac** [comment]
I saw your message to core-livs-dev: https://mail.openjdk.java.net/pipermail/core-libs-dev/2020-December/072784.html

Excellent! Thank you again!

**Pull request closed without merging**
