### PR TITLE
Reworded thread locals section

### PR DESCRIPTION
**Pull request by cayhorstmann**

### CODE REVIEW

**Comment by marchof** [comment]
Somehow the latest commit makes GitHub think this is a binary file now. As soon as I'm nearby a real computer again I will try to sort this out.

@cayhorstmann Alternatively do you have a chance to re-apply the change on the latest master commit?

**Comment by cayhorstmann** [comment]
I don't know how this happened...perhaps a cosmic ray flipped a bit, and the file was no longer UTF-8. It is again now.

**Comment by marchof** [comment]
Hi @cayhorstmann, I rebased/squashed you changes on `master`.  Now GitHub is happy. Can you please double-check that the diff here looks good to you.?

**Comment by cayhorstmann** [comment]
Thanks, that's the change that I intended for review.

**Review by marchof — APPROVED** [review]

**Pull request merged**
