### PR TITLE
Adding 16 for Zulu

### PR DESCRIPTION
**Pull request by geertjanw**

### CODE REVIEW

**Comment by marchof** [comment]
I wonder whether it would make sense to have a separate product per release. This would come with the following benefits:

1) Version specific download URLs (e.g. https://www.azul.com/downloads/zulu-community/?version=java-16-ea)
2) Version specific supported architectures

I think something similar was already done on foojay.io: https://foojay.io/almanac/jdk-16/

**Comment by geertjanw** [comment]
Yes, this is a valid URL: https://www.azul.com/downloads/zulu-community/?version=java-16-ea

What must I change in the pull request?

**Comment by marchof** [comment]
I would propose to have a separate product for every release, see for example Oracle. This allows to provide release specific information like download link or platforms.

I think this was already done on foojay.io. Maybe you can get the content from there?

**Comment by marchof** [comment]
Resolved by 34ba9e16613dbfb73c8e9fea6e8f10e0c14e0be8

**Pull request closed without merging**
